### ISSUE TITLE
fpie command error in colab notebook

### ISSUE THREAD

**Issue by himmetozcan** [FusionBrainLab/StyleFeatureEditor#12]
Thanks for providing this repo. I got errors while running the colab notebook. It says cant find the fpie command. What is this fpie in simple_runner.py script?

```
    subprocess.run(
            ["fpie", "-s", orig_img_pth, "-m", "mask.jpg", "-t", "edited.png", "-o", unaligned_path, "-n",
             "5000", "-b", "taichi-gpu", "-g", "src"],
            check=True
        )
```
Found 1 faces, getting the largest
Save aligned image to editing_res/scarlet/scarlet_aligned.jpg
Prepearing mask
/content/StyleFeatureEditor/models/farl/farl.py:38: FutureWarning: You are using torch.load with weights_only=False (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for weights_only will be flipped to True. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via torch.serialization.add_safe_globals. We recommend you start setting weights_only=True for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
pretrained_dict = torch.load(
Done
Use mask from editing_res/scarlet/scarlet_aligned_mask.jpg
FileNotFoundError Traceback (most recent call last)
in <cell line: 5>()
3 target_prompt = "face with fire hair"
4 disentanglement = 0.1
----> 5 runner.edit(
6 orig_img_pth="notebook/images/scarlet.jpg",
7 editing_name=f"styleclip_global_{neutral_prompt}{target_prompt}{disentanglement}",

4 frames
[/content/StyleFeatureEditor/runners/simple_runner.py](https://localhost:8080/#) in edit(self, orig_img_pth, editing_name, edited_power, save_pth, align, use_mask, mask_trashold, mask_path, save_e4e, save_inversion)
202 if align:
203 unaligned_path = save_pth.parents[0] / (save_pth.stem + "_unaligned.jpg")
--> 204 unalign(edited_image, unalign_dict, orig_img_pth, unaligned_path)
205
206 return edited_image

[/content/StyleFeatureEditor/runners/simple_runner.py](https://localhost:8080/#) in unalign(edited_image, unalign_dict, orig_img_pth, unaligned_path)
105 PIL.Image.fromarray(np.uint8(np.clip(np.rint((1 - mask) * 255), 0, 255)), 'RGB').save("mask.jpg")
106
--> 107 subprocess.run(
108 ["fpie", "-s", orig_img_pth, "-m", "mask.jpg", "-t", "edited.png", "-o", unaligned_path, "-n",
109 "5000", "-b", "taichi-gpu", "-g", "src"],

[/usr/lib/python3.10/subprocess.py](https://localhost:8080/#) in run(input, capture_output, timeout, check, *popenargs, **kwargs)
501 kwargs['stderr'] = PIPE
502
--> 503 with Popen(*popenargs, **kwargs) as process:
504 try:
505 stdout, stderr = process.communicate(input, timeout=timeout)

[/usr/lib/python3.10/subprocess.py](https://localhost:8080/#) in init(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, user, group, extra_groups, encoding, errors, text, umask, pipesize)
969 encoding=encoding, errors=errors)
970
--> 971 self._execute_child(args, executable, preexec_fn, close_fds,
972 pass_fds, cwd, env,
973 startupinfo, creationflags, shell,

[/usr/lib/python3.10/subprocess.py](https://localhost:8080/#) in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, restore_signals, gid, gids, uid, umask, start_new_session)
1861 if errno_num != 0:
1862 err_msg = os.strerror(errno_num)
-> 1863 raise child_exception_type(errno_num, err_msg, err_filename)
1864 raise child_exception_type(err_msg)
1865

FileNotFoundError: [Errno 2] No such file or directory: 'fpie'

**Comment by retir** [comment]
Hi, you can fix this with `!pip install fpie` in your notebook. However, we have updated our collab so that now `fpie` is installed during the installation of other packages. If the problem is solved, please close this issue.

**Comment by retir** [comment]
Has the error been solved? Can we close the issue?
