### ISSUE TITLE
how to train other models

### ISSUE THREAD

**Issue by qiqi0308** [FusionBrainLab/StyleFeatureEditor#13]
Hello,

Your model performs excellently, thank you. However, I am still interested in understanding how to train other models, such as for pink hair or dreadlocks. What should I pay attention to when collecting a training dataset? I would greatly appreciate any effective advice you can provide.

Thank you!

**Comment by retir** [comment]
Hi, if I understand correctly, you are talking about the way to create a model that would provide new edits. However, our approach does not give new editings, it is related to how to invert the image into stylegan latent space in a way that it can be correctly edited by other editing methods (such as InterfaceGAN, Deltaedit and e.t.c.). If your goal is to find new editing directions, better check [StyleClip](https://arxiv.org/abs/2103.17249), [DeltaEdit ](https://arxiv.org/abs/2303.06285) or [StyleEntity](https://openaccess.thecvf.com/content/CVPR2024/papers/Feng_Named_Entity_Driven_Zero-Shot_Image_Manipulation_CVPR_2024_paper.pdf).
