### ISSUE TITLE
Replicating  Metrics

### ISSUE THREAD

**Issue by JhEdLp** [FusionBrainLab/StyleFeatureEditor#4]
Hi, Thanks for releasing the code!

I'm encountering difficulties replicating the metrics reported in the main document. I'm wondering if the mask=True flag is used during the inference step when calculating these metrics.

Specifically, are the metrics calculated using Metric(Mask * I, Mask * I'), where Mask is applied to both input images before computing the Metric?

Thanks,

**Comment by retir** [comment]
Hi, thank you for your question! 

No, we did not use any masking when calculating the metrics. We just used our script and first infer our method:
```bash
python scripts/inference.py \
    exp.config_dir=configs \
    exp.config=fse_inference.yaml \
    model.checkpoint_path="pretrained_models/sfe_editor_light.pt" \
    data.inference_dir="path/to/original/images" \
    exp.output_dir="results"
```
and then calculate inversion metrics:
``` bash
python scripts/calculate_metrics.py \
    --orig_path="path/to/original/images" \
    --reconstr_path="results/inversion" \
    --metrics l2 lpips fid
```
Could you tell us what data you use to calculate the metrics and what metrics values you get?

**Comment by retir** [comment]
Did our comment help solve the problem? Can we close the issue?

**Comment by JhEdLp** [comment]
Yes, your answer helped me. 

Thanks.
