### ISSUE TITLE
How to get more attributes?

### ISSUE THREAD

**Issue by shartoo** [FusionBrainLab/StyleFeatureEditor#6]
The project provides a variety of attribute editing directions, but the current attribute editing methods such as GANSpace, InterfaceGAN only a small number of attributes can get better editing results, which is due to the natural entanglement of w+ space. Since this project is based on the new FS space, is it possible to train new attribute editing models in FS space and are there some useful suggestions? Thanks!

**Comment by retir** [comment]
Thank you for the question! Unfortunately, there are no works related to finding editing directions in F-space. However, this idea seems quite natural, and for now our team is researching the ways to do it correctly. So, stay tuned for our releases 😉
