### ISSUE TITLE
Celeba HQ Test set

### ISSUE THREAD

**Issue by JhEdLp** [FusionBrainLab/StyleFeatureEditor#7]
Hi there,

I'm working on a project that requires the test set of the CelebA-HQ dataset. Could you please provide information on how to obtain the list of filenames for this set?

Ideally, a text file containing the filenames would be helpful. If this isn't possible, could you share a link to where this information can be found?

Thanks in advance.

**Comment by retir** [comment]
Hello, you can find information about the official split of Celeba HQ [here](https://github.com/lyndonzheng/Pluralistic-Inpainting/issues/30). We also provide a [test_split.txt](https://github.com/user-attachments/files/16567878/test_split.txt) file with image names related to the test part from this discussion.
