### ISSUE TITLE
`e4e_encoder`  in models/methods.py seems useless?

### ISSUE THREAD

**Issue by shartoo** [FusionBrainLab/StyleFeatureEditor#8]
I debuged the `FSEInferenceRunner` code and found that  an `e4e_encoder`  seemed total useless?

```
 print("Loading E4E from", self.opts.e4e_path)
 ckpt = torch.load(self.opts.e4e_path, map_location="cpu")
 self.e4e_encoder.load_state_dict(get_keys(ckpt, "encoder"), strict=True)
 self.e4e_encoder = self.e4e_encoder.eval().to(self.device)
 toogle_grad(self.e4e_encoder, False)
```

**Comment by retir** [comment]
Hi, actually `e4e_encoder` has no use in `models/methods.py` but it is used in `runners/inference_runners.py` and in `runners/training_runners.py`. We made it a part of methods because methods contain all the necessary parts for editing ( such as all encoders, decoders and etc.).

**Comment by shartoo** [comment]
So `w_recon`  from `inverter.fs_backbone` becomes useless during inference? It is only used to correlate edit directions during training?

**Comment by retir** [comment]
No, `w_recon` is used as w-latents for inversion (and as w_0 during editing) -- you can see the use of `orig_latents` (which is litterally `w_recon` -- see `_run_on_batch`) in the `_run_editing_on_batch` method of the inference runner.

**Comment by shartoo** [comment]
Thank you for your patience.  Here's some of my understanding

##### image inversion stage

During an image inversion, the pipeline of e4e  namely  `w_e4e` from e4e encoder is totally replace by `w_recon` from `inverters.fs_backbon` , if no editing in considered. A `w_e4e` inversed from e4e in  `_run_on_batch` methods is just a preparing for the next editing stage.

```
class FSEInferenceRunner(BaseInferenceRunner):
    def _run_on_batch(self, inputs):
        images, w_recon, fused_feat, predicted_feat = self.method(inputs, return_latents=True)
```
the code actually calls `methods.py-->FSEFull.forward()` (no e4e component needed)
```
 def forward(self, x, return_latents=False, n_iter=1e5):
        x = F.interpolate(x, size=(256, 256), mode="bilinear", align_corners=False)
        with torch.no_grad():
            w_recon, predicted_feat = self.inverter.fs_backbone(x)
            w_recon = w_recon + self.latent_avg
            _, w_feats = self.decoder( [w_recon], input_is_latent=True, return_features=True, is_stylespace=False,           randomize_noise=False,
                early_stop=64
            )
            w_feat = w_feats[9]  # bs x 512 x 64 x 64 
            fused_feat = self.inverter.fuser(torch.cat([predicted_feat, w_feat], dim=1))
            delta = torch.zeros_like(fused_feat)  # inversion case

        edited_feat = self.encoder(torch.cat([fused_feat, delta], dim=1))
        feats = [None] * 9 + [edited_feat] + [None] * (17 - 9)
        images, _ = self.decoder( [w_recon], input_is_latent=True,return_features=True,new_features=feats,feature_scale=min(1.0, 0.0001 * n_iter),is_stylespace=False,randomize_noise=False
        )
```

#### image edit stage
The only role of `w_e4e`  is just for getting  the `edited_feat` ($512\times 64\times 64$), the `w_recon` is still the main component to generate edit image.

we got below inputs from inversion stage 

+ `w_e4e`  from e4e
+ `w_recon` from `inverster.fs_backbone` ,now named by `latent`

most of the code is used for getting edit feature

![235](https://github.com/user-attachments/assets/371eb298-029b-4aae-90c4-1553300e1568)

**Comment by retir** [comment]
Yes, you are correct! Do you have any other questions?

**Comment by shartoo** [comment]
I' clear now, thank you!
